version: '3'
services:
  web:
    image: php:7.4-apache
    ports:
      - "13:87"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: 123@123Aa
  phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin
  ports:
  - '13:87'
  restart: always
  environmet:
  PMA_HOST: db
  depends_on:
  - db
